from __future__ import annotations

from collections import Counter
from typing import List

from .models import Report, Finding


def summarize_report_md(report: Report, max_items: int = 10) -> str:
    counts = Counter([f.severity for f in report.findings])
    high = counts.get("HIGH", 0)
    med = counts.get("MEDIUM", 0)
    low = counts.get("LOW", 0)

    lines: List[str] = []
    lines.append("## 🛡️ SpecGuard LLM Report")
    lines.append("")
    lines.append(f"**Base..Head:** `{report.meta.base}..{report.meta.head}`")
    lines.append(f"**Deterministic:** `{report.meta.deterministic}`  |  **Cache hit:** `{report.meta.cache_hit}`")
    if report.meta.llm_provider:
        lines.append(f"**LLM:** `{report.meta.llm_provider}` / `{report.meta.model}`")
    else:
        lines.append("**LLM:** `disabled` (heuristics only)")
    lines.append("")
    lines.append(f"### Findings summary: HIGH={high}  MEDIUM={med}  LOW={low}")
    lines.append("")

    def fmt_item(f: Finding) -> str:
        link_part = f" ([spec]({f.links[0]}))" if f.links else ""
        conf = f"{f.confidence:.2f}"
        return f"- **{f.severity}** `{f.rule_id}` (conf {conf}) — {f.rule_summary}{link_part}"

    for f in report.findings[:max_items]:
        lines.append(fmt_item(f))

    if len(report.findings) > max_items:
        lines.append(f"... and {len(report.findings) - max_items} more. See JSON artifact for full report.")

    lines.append("")
    lines.append("_Generated by SpecGuard LLM_")
    return "\n".join(lines) + "\n"
